Oneflow-Inc/oneflow-documentation

README.md
=> Fix_alexnet

cn/docs/extended_topics/consistent_mirrored.md, en/docs/extended_topics/consistent_mirrored.md
修复consistent_mirrored的英文文档和中文文档
=> Fix_consistent_mirrored doc

cn/docs/extended_topics/model_mixed_parallel.md, en/docs/extended_topics/consistent_mirrored.md, en/docs/extended_topics/job_function_define_call.md, en/docs/extended_topics/model_mixed_parallel.md
=> Fix consistent parallelism

cn/docs/extended_topics/model_mixed_parallel.md, en/docs/extended_topics/job_function_define_call.md, en/docs/extended_topics/model_mixed_parallel.md
=> Fix model mixed

en/docs/extended_topics/how_to_make_ofdataset.md
=> fix ofdataset en docs

en/docs/extended_topics/watch_watch_diff.md
=> fix watch diff

cn/docs/extended_topics/debug_by_vscode.md, en/docs/extended_topics/debug_by_vscode.md
=> fix_debug_vscode_en_cn_doc

en/docs/contribute/intro.md
=> fix intro in en docs

en/docs/code/extended_topics/hybrid_parallelism_lenet.py, en/docs/code/extended_topics/hybrid_parallelism_mlp.py, en/docs/extended_topics/model_mixed_parallel.md
=> fix link in en docs

cn/docs/basics_topics/model_load_save.md, en/docs/basics_topics/model_load_save.md
=> fix model load and save

en/docs/basics_topics/essentials_of_oneflow.md
=> fix change

en/docs/basics_topics/model_load_save.md
1、scenario ->Sences
2、We all use  flow.train -> We use  flow.train
3、interface -> interfaces
4、we need use ->we need to use 
5、According the model->According to the model
=> change and review

en/docs/basics_topics/model_load_save.md
=> review mode_load_save.md again

cn/docs/extended_topics/user_op.md
=> add doc of  `support UserOpAttrType::kAtString -> std::string`

cn/docs/basics_topics/optimizer_in_function_config.md, en/docs/basics_topics/optimizer_in_function_config.md
修复global function配置"test" 为 "predict"
=> fix test to predict

cn/docs/code/extended_topics/img_to_ofrecord/img2ofrecord.py, cn/docs/code/extended_topics/ofrecord_from_string.py, cn/docs/code/extended_topics/ofrecord_to_string.py, en/docs/code/extended_topics/ofrecord_from_string.py, en/docs/code/extended_topics/ofrecord_to_string.py
=> fix serialize

cn/docs/basics_topics/data_input.md
a small typo correction from "是" to "时".
=> typo correction.

cn/docs/basics_topics/data_input.md, cn/docs/basics_topics/distributed_train.md, en/docs/basics_topics/distributed_train.md
docker -v is used for volume mapping. 
docker -p is used for port mapping.
=> Document correction. 

cn/docs/extended_topics/oneflow_convert_tools.md, en/docs/extended_topics/oneflow_convert_tools.md, en/mkdocs.yml
=> add oneflow_onnx docs

cn/docs/basics/02_tensor.md
=> PR for 2.2_tensor demo 

cn/docs/basics/04_build_network.md
发现了中文文档basics/04_build_network.md的错误并修改
=> resize by LiuNing

cn/docs/code/parallelism/ddp_train.py, cn/docs/parallelism/05_ddp.md, cn/docs/parallelism/06_pipeline.md, cn/mkdocs.yml
本 PR 依赖 https://github.com/Oneflow-Inc/oneflow/pull/6254 这个 PR，只有在 6254 合并后，本文档 PR 才能合并发布。
=> add pipeline parallelsim article

cn/docs/parallelism/03_consistent_tensor.md
=> change flow in output into oneflow

cn/docs/basics/01_quickstart.md, cn/docs/basics/03_dataset_dataloader.md, en/docs/basics/01_quickstart.md, en/docs/basics/03_dataset_dataloader.md
MNIST -> FashionMNIST
remove the last relu in NeuralNetwork 
add device
=> fix quickstart

cn/docs/basics/01_quickstart.md, cn/docs/basics/02_tensor.md, cn/docs/basics/03_dataset_dataloader.md, cn/docs/basics/04_build_network.md, cn/docs/basics/05_autograd.md, cn/docs/basics/06_optimization.md, cn/docs/basics/07_model_load_save.md, cn/docs/basics/08_nn_graph.md, en/docs/basics/01_quickstart.md, en/docs/basics/02_tensor.md, en/docs/basics/03_dataset_dataloader.md, en/docs/basics/04_build_network.md, en/docs/basics/05_autograd.md, en/docs/basics/06_optimization.md, en/docs/basics/07_model_load_save.md, en/docs/basics/08_nn_graph.md
fix some small typos to make sure the website builds well.
=> fix some typos in the documentation

en/docs/basics/08_nn_graph.md
根据 https://github.com/Oneflow-Inc/oneflow-documentation/pull/391 对英文版 en\docs\basics\08_nn_graph.md 进行了更新
=> translated 08_nn_graph

cn/docs/basics/07_model_load_save.md, en/docs/basics/07_model_load_save.md
=> solve issue #387

cn/mkdocs.yml
remove the disqs block because of useless advertisement
=> remove disqs

en/docs/parallelism/01_introduction.md
=> revise_translate0221

cn/docs/parallelism/04_2d-sbp.md, en/docs/parallelism/04_2d-sbp.md
根据 https://github.com/Oneflow-Inc/oneflow-documentation/issues/443 给 “2D SBP” 一文添加代码示例
- 中文版预览：https://alive1024.github.io/oneflow-documentation/master/parallelism/04_2d-sbp.html#2d-sbp_2
- 英文版预览：https://alive1024.github.io/oneflow-documentation/en/master/parallelism/04_2d-sbp.html#an-example-of-using-2d-sbp
=> Add 2D SDP Example

cn/docs/parallelism/03_consistent_tensor.md, en/docs/parallelism/03_consistent_tensor.md
今天看教程文档的时候发现这个还没及时更新，顺手更新下。
来源：https://github.com/Oneflow-Inc/oneflow/pull/8411
=> Modify split axis to dim

cn/mkdocs.yml
=> change API web site

cn/docs/cookies/global_tensor.md, cn/mkdocs.yml
主要改动：
- 修正一些格式
- 修改级补充部分表述
- 修正代码中的小错误
- 在 cn/mkdocs.yml 中新增此文章
预览：https://alive1024.github.io/oneflow-documentation/master/cookies/global_tensor.html
=> Refine "使用 Global Tensor 进行多机多设备编程"

cn/docs/parallelism/05_ddp.md
=> update DistributedDataParallel url

cn/docs/assets/install-selector.js, en/docs/assets/install-selector.js
因为 v0.8.1 只有 tag 没有发布版本，所以首页自动显示的命令会提示包找不到。
临时解决方案，把 v0.8.1 替换为 v0.8.0
=> refine bug about v0.8.1

cn/docs/cookies/zero.md, cn/docs/parallelism/06_pipeline.md, en/docs/cookies/zero.md, en/docs/parallelism/06_pipeline.md
Update zero and pipeline usage doc.
=> Update doc of graph api

cn/docs/cookies/activation_checkpointing.md, cn/docs/cookies/amp.md, en/docs/basics/02_tensor.md, en/docs/cookies/activation_checkpointing.md, en/docs/cookies/amp.md
更新 amp、checkpoing 2 篇文章的 API URL
=> update api urls

cn/docs/cookies/oneflow_torch.md
=> add para for mock

.github/workflows/markdown-ci.yml, .github/workflows/pub.yml, cn/docs/cookies/lr_scale.md, cn/mkdocs.yml, scripts/markdown_ci/configs/guide_lr_scale.yml
更新了guide关于分层lr的设置的用户文档
主要和 https://github.com/Oneflow-Inc/OneTeam/issues/1644 相关
网页预览https://wraythh.github.io/oneflow-documentation/master/cookies/lr_scale.html
=> 分层lr_scale使用指南
